---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  # - jest
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true
  jest: true

extends:
  - 'airbnb-base'
  # - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  class-methods-use-this: 0
  import/no-unresolved: 0
  no-undef: 0
  no-param-reassign: 0
